name: Dispatcher
on:
  workflow_run:
    workflows: [ release-actions ]
    types:
      - completed

jobs:
  dispatch:
    name: Dispatch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['socialbaking/vouch-api']
    timeout-minutes: 5
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_VOUCH }}
          repository: ${{ matrix.repo }}
          event-type: repository_update_event